version: "3"

services:
  web:
    image: python
    container_name: web
    volumes:
      - ./web/:/app
    command: bash -c "pip install -r /app/requirements.txt && python3 /app/web.py"
    ports:
      - 80:80
    networks:
      mynetwork:
        ipv4_address: 192.168.10.2
    depends_on:
      - db

  db:
    image: mysql
    container_name: db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=users
    ports:
      - 3306:3306
    volumes:
      - ./db/inicio.sql:/docker-entrypoint-initdb.d/inicio.sql
    command: --init-file /docker-entrypoint-initdb.d/inicio.sql
    networks:
      mynetwork:
        ipv4_address: 192.168.10.3

  api:
    image: python
    container_name: api
    volumes:
      - ./api/:/app
    command: bash -c "pip install -r /app/requirements.txt && python3 /app/api.py"
    ports:
      - 5600:5600
    networks:
     mynetwork:
       ipv4_address: 192.168.10.4


networks:
  mynetwork:
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24